# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: TSTL Build && Artifact Upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Building Artifact
    runs-on: ubuntu-latest

    env:
      NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      
    steps:  
    - uses: actions/checkout@v2
    - name: Use Node.js [16.x]
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install && npm run-script git-publish
    - run: cp package.json ./dist/ && cp package-lock.json ./dist/ && cp README.md ./dist/ && cp LICENSE ./dist/ && cp .npmrc ./dist/
    - uses: actions/upload-artifact@v2.2.4
      with:
        path: ./dist/
        name: build

  build_tests:
    name: Acceptance Testing
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js [16.x]
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install && npm run-script build-testing
    - uses: actions/upload-artifact@v2.2.4
      with:
        path: ./testing/
        name: testing
    - name: Install Lua
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "luajit-2.1.0-beta3"
    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@v4.0.0
    - run: luarocks install busted
    - run: cd testing && ls && busted
        
  deploy: 
    name: Deploy To NPM
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '@deploy')"
    needs: [build, build_tests]
    env:
      NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
    
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: build
          path: .
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - name: npm bump
        uses: bcomnes/npm-bump@v2.0.2
        with:
          git_email: qfluxstudio@gmail.com
          git_username: github.actor
          newversion: patch
          push_version_commit: true
          npm_token: ${{secrets.NPM_ACCESS_TOKEN}}
